### ISSUE TITLE
zkg refresh aggregate error

### ISSUE THREAD

**Issue by 0xxon** [zeek/package-manager#53]
zkg errors out on python 2.7 for me - I assume this might have to do with some of the recent additions to the repository.

```
$ zkg --verbose refresh --aggregate
Refresh package source: zeek
Traceback (most recent call last):
  File "/Users/johanna/python/bin/zkg", line 2215, in <module>
    main()
  File "/Users/johanna/python/bin/zkg", line 2211, in main
    args.run_cmd(manager, args, config, configfile)
  File "/Users/johanna/python/bin/zkg", line 952, in cmd_refresh
    source, aggregate=args.aggregate, push=args.push)
  File "/Users/johanna/python/lib/python2.7/site-packages/zeekpkg/manager.py", line 782, in refresh_source
    parser.write(f)
  File "/Users/johanna/python/lib/python2.7/site-packages/backports/configparser/__init__.py", line 939, in write
    self._sections[section].items(), d)
  File "/Users/johanna/python/lib/python2.7/site-packages/backports/configparser/__init__.py", line 951, in _write_section
    fp.write("{0}{1}\n".format(key, value))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 47-48: ordinal not in range(128)
```

**Comment by jsiwek** [comment]
Yeah, I see the same under Python2 due to `emojifier` metadata file:

https://github.com/emojifier/emojifier/blob/4ddc71bf8106373cac35949c8cd3202fb3ef6689/zkg.meta#L2

The default `configparser` behavior in Python3 works fine, so I'm going to bet on this being uncommon enough that I'll ask case-by-case to use ASCII-only in metadata files before Jan 1, 2020 comes and Python2 is officially EOL rather than making a code change in `zkg` to support it.  Already made a PR to `emojifier` to fix it.

**Comment by jsiwek** [comment]
No plans to do anything more here as it pertains to EOL Python 2.x
